Fix cpu count on macOS.
Fixes the following error observed on macOS hosts:

  Traceback (most recent call last):
    File "/Users/nick/Code/python/boot-utils/boot-qemu.py", line 724, in <module>
      cfg = setup_cfg(args)
    File "/Users/nick/Code/python/boot-utils/boot-qemu.py", line 242, in setup_cfg
      "smp_value": get_smp_value(args),
    File "/Users/nick/Code/python/boot-utils/boot-qemu.py", line 198, in get_smp_value
      usable_cpus = len(os.sched_getaffinity(0))
  AttributeError: module 'os' has no attribute 'sched_getaffinity'

The issue is that the `os` module in python does not have a
`sched_getaffinity` method on macOS.

Signed-off-by: Nick Desaulniers <nick.desaulniers@gmail.com>